server:
  port: 8084
spring:
  application:
    name: auth-service
#  datasource:
#    url: jdbc:postgresql://postgres-auth-users:5432/auth-users-db

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
