server:
  port: 8084
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-auth-users:5432/auth-users-db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres-auth-users:5432/auth-users-db
    user: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
