server:
  port: 8082
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: user
    password: pass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
