server:
  port: 8082
spring:
  application:
    name: event-service
  main:
    web-application-type: reactive

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api/v1/event/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"