server:
  port: 8082
spring:
  application:
    name: event-service
  main:
    web-application-type: reactive

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"