server:
  port: 8082
spring:
  application:
    name: event-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/events_db
    username: postgres
    password: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/events_db
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/events_db
    user: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 