server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: user-service-user
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/**
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service-swagger
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/v3/api-docs
              filters:
                - StripPrefix=3

            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/v1/event/**
            - id: group-event-service
              uri: lb://group-event-service
              predicates:
                - Path=/api/v1/groupEvent/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
