server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: false
          routes:
            - id: user-service-user
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/**
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**
            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/v1/event/**

            - id: group-event-service-swagger
              uri: lb://group-event-service
              predicates:
                - Path=/api/v1/group-event/v3/api-docs
              filters:
                - StripPrefix=3

            - id: group-event-service
              uri: lb://group-event-service
              predicates:
                - Path=/api/v1/group-event/**



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/v1/user/v3/api-docs
        name: User Service
      - url: /api/v1/event/v3/api-docs
        name: Event Service
      - url: /api/v1/groupEvent/v3/api-docs
        name: Group Event Service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
