server:
  port: 8083
spring:
  application:
    name: group-event-service
  main:
    web-application-type: reactive

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"