server:
  port: 8083
spring:
  application:
    name: group-event-service
  datasource:
    url: jdbc:postgresql://postgres-group-events:5432/group-events-db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres-group-events:5432/group-events-db
    user: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true