server:
  port: 8083
spring:
  application:
    name: group-event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/group-events-db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/