server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: pass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/